### ISSUE TITLE
primary keys absolutely necessary? could unique index also do the job?

### ISSUE THREAD

**Issue by ghof050472** [realrolfje/anonimatron#8]
Hi,
we would like to anonymize data in Actian Ingres 10.2 DBMS. We were able to add the Ingres JDBC driver iijdbc.jar to the propriate subdirectory and to create a config file.

Output looks like a successful connect to the DB but then it says.
Table dataansprcrm does not contain a primary key and can not be anonymyzed

And indeed, the table really does not a primary key constraint.

Questions: 

1. could the program also use an existing unique index instead of a primary key?
2 Ingres uses some "hidden" field TID (=tuple id), could anonimatron make use of this field?
3 if 1 and 2 are not possible...   could the program "auto generate"  just use the combinatin of all existing columns of the table as a key

TIA
Gerhard

**Comment by realrolfje** [comment]
Hello Gerhard, thanks for your interest and suggestion. I do not have an Ingress database to test with right now, but I can answer your questions:

1. The program requires a unique key because it is using an updatable result set for performance reasons. Most (all?) databases require a primary key when you want to update rows returned by a select statement.
2. I do not have an ingress database to test that on. The [Ingres Documentation](https://communities.actian.com/s/article/Ingres-10-2-SQL-Reference-Guide) does not reference this TID or Tuple Id. I did find some forum posts which suggest that the Tuple Id is based on the page and offset of a row, and that the Tuple Id of a row can change during the lifetime of a row. Can you point me to documentation on the Tuple Id so that I can check if this us meant to be used as a primary key?
3. No, I can not generate a key based on all row values for two reasons. The first is because of the updatable result set, see point 1. The second is that anonimatron does not make structural changes to your database (no DDL), it only replaces data in cells.

Am I correct that the data in datansprcrm is referenced by the unique index, and that you can not or are not allowed to change that column to be a unique key? I am not familiar with Ingres, is there a special reason why this is done this way?

**Comment by ghof050472** [comment]
Hello,
it's no specialty of the Ingres product that we have not a primary key. The cause is rather that the programmers of the application did not define any.
I'm well aware that this is rather strange, but they did it...

Concerning TID:
in Ingres you can do
   select * from table
   --> get all "normal" data from the table
   select tid, * from
   --> get also the tuple id

Not documented (AFAIK), but possible to do:
   update table set firstname = 'John' where tid = 123

Regards
Gerhard

**Comment by ghof050472** [comment]
Similar to Ingres' TID is the ROWID in Oracle and the CTID in PostgreSQL:
https://docs.oracle.com/cd/B19306_01/server.102/b14200/pseudocolumns008.htm
https://www.postgresql.org/docs/8.2/static/ddl-system-columns.html

**Comment by ghof050472** [comment]
OK, I think I have found a practical way to use anonimatron anyway.
alter table dataansprcrm add column pkid integer not null with default 
   --> add a column pkid to the table

update dataansprcrm set pkid = tid 
    --> use the Ingres tuple id as pkid value

alter table dataansprcrm add primary key(pkid) 
    --> define pkid as the primary key for the table

And after using anonimatron I will drop away the primary keys cause I want the structures to be as original as possible for our software testing.

Is it possible to put such user defined SQLs in the XML config file?
Otherwise I would create some pre and post BAT file.

**Comment by realrolfje** [comment]
I have seen other situations where the database is slightly altered to make Anonimatron work, and then the changes are reversed after the run. Usually this is on a copy of the production database, which you probably have a script for anyway.

If so, I think it is best to add the changes you describe in the copy script that copies the production database:

1. copy production database
2. modify the copy (add keys)
3. call anonimatron
4. revert the changes to the copy (remove keys)
